// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFBzvoBEsdaLewLRt_1QqFGOjA3CI0o_s',
    appId: '1:628343819365:web:46ff76093fea0f5ef1ca8c',
    messagingSenderId: '628343819365',
    projectId: 'backtohome-d6663',
    authDomain: 'backtohome-d6663.firebaseapp.com',
    storageBucket: 'backtohome-d6663.firebasestorage.app',
    measurementId: 'G-1X2SK4NH80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgaS7LVnZpLjTo_v_2w7OFGmPsTU0YX-A',
    appId: '1:628343819365:android:05a82c1e77d06b12f1ca8c',
    messagingSenderId: '628343819365',
    projectId: 'backtohome-d6663',
    storageBucket: 'backtohome-d6663.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArAb_032AGk7pDaWlsP5Wx-0eANiF9gmc',
    appId: '1:628343819365:ios:c6bc3c1f2e61d3fdf1ca8c',
    messagingSenderId: '628343819365',
    projectId: 'backtohome-d6663',
    storageBucket: 'backtohome-d6663.firebasestorage.app',
    iosBundleId: 'com.backtohome.backtohomeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArAb_032AGk7pDaWlsP5Wx-0eANiF9gmc',
    appId: '1:628343819365:ios:c6bc3c1f2e61d3fdf1ca8c',
    messagingSenderId: '628343819365',
    projectId: 'backtohome-d6663',
    storageBucket: 'backtohome-d6663.firebasestorage.app',
    iosBundleId: 'com.backtohome.backtohomeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFBzvoBEsdaLewLRt_1QqFGOjA3CI0o_s',
    appId: '1:628343819365:web:e158ac43db6c1f93f1ca8c',
    messagingSenderId: '628343819365',
    projectId: 'backtohome-d6663',
    authDomain: 'backtohome-d6663.firebaseapp.com',
    storageBucket: 'backtohome-d6663.firebasestorage.app',
    measurementId: 'G-GMS20HJ69W',
  );
}
